spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: f1
          uri: http://localhost:8082/
          predicates:
            - Path=/something/**, /something/api/**
        - id: f2
          uri: http://localhost:8084/
          predicates:
            - Path=/api/normal/**, /normal/**, /normal/api**
        - id: f3
          uri: https://google.com
          predicates:
            - Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/TestRealm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/TestRealm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: GateWayClient
            client-secret: ccd47a5a-b115-42c6-9d7b-5e20188d2768
